package view;

import base.SyncedListModel;
import com.sun.org.apache.xpath.internal.operations.Bool;
import model.Product;
import util.*;
import util.Event;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

public class ProductSelector extends MyFrame {
    private JList<Product> productList;
    private JButton selectButton;
    private JButton cancelButton;
    private JPanel mainPanel;

    private ArrayListModel<Product> productsModel;
    public Event<List<Product>> onSelect;

    public ProductSelector() {
        super();

        setTitle("Selecione:");
        setSize(400, 300);

        setContentPane(mainPanel);

        onSelect = new Event<>();


        onOpen.addListener(e -> {
            centerOnScreen();
            clearForm();

            if (e.data.length > 0 && e.data[0] instanceof ArrayList) {
                productsModel.setList((List) e.data[0]);
            }

            if (e.data.length > 1 && e.data[1] instanceof Boolean) {
                Boolean multiple = (Boolean) e.data[1];

                productList.setSelectionMode(multiple ? ListSelectionModel.MULTIPLE_INTERVAL_SELECTION : ListSelectionModel.SINGLE_SELECTION);
            }

            onSelect.clear();
        });


        // List
        productsModel = new ArrayListModel<>(new ArrayList<>());
        productList.setModel(productsModel);
        productList.addListSelectionListener(e -> {
            selectButton.setEnabled(true);
        });
        productList.addMouseListener(new ListDoubleClickAdapter<Product>(x -> {
            select();
            close();
        }));

        productList.setCellRenderer(new StringCellRenderer<Product>(Product::getName));


        selectButton.addActionListener(e -> {
            select();
            close();
        });

        cancelButton.addActionListener(e -> close());
    }

    private void clearForm() {
        productList.clearSelection();
        selectButton.setEnabled(false);
    }

    private void select() {
        List<Product> selected = productList.getSelectedValuesList();
        onSelect.emit(selected);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        final JScrollPane scrollPane1 = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(scrollPane1, gbc);
        productList = new JList();
        scrollPane1.setViewportView(productList);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(panel1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer2, gbc);
        selectButton = new JButton();
        selectButton.setEnabled(false);
        selectButton.setText("Selecionar");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(selectButton, gbc);
        cancelButton = new JButton();
        cancelButton.setText("Cancel");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(cancelButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
